In [ ]:
import numpy as np
import matplotlib.pyplot as plt


Matrices Operations

1. Addition and Substraction

- Rule: Only Matrices with the same shape are allowed to add  and substract

In [9]:
# addition of the same shape
a=np.array(([1,3,5],[6,7,8]))
b=np.array(([1,3,5],[6,7,8]))
print(a+b)

[[ 2  6 10]
 [12 14 16]]


In [10]:
matrix_a=np.random.randint(1,10,size=(3,3))
matrix_b=np.random.randint(1,10,size=(3,3))
print(matrix_a)
print(matrix_b)
sum = matrix_a + matrix_b
print(sum)

[[1 7 5]
 [4 8 6]
 [8 6 3]]
[[6 5 6]
 [2 6 2]
 [8 8 4]]
[[ 7 12 11]
 [ 6 14  8]
 [16 14  7]]


In [11]:
# adding two matrices with different shapes
matrix_a=np.random.randint(1,10,size=(4,3))
matrix_b=np.random.randint(1,10,size=(3,3))
print(matrix_a)
print(matrix_b)
sum = matrix_a + matrix_b
print(sum)

[[3 3 6]
 [4 7 6]
 [8 7 9]
 [7 7 5]]
[[9 6 4]
 [3 6 2]
 [3 4 7]]


ValueError: operands could not be broadcast together with shapes (4,3) (3,3) 

In [12]:
# Substaction
matrix_a=np.random.randint(1,10,size=(3,3))
matrix_b=np.random.randint(1,10,size=(3,3))
print(matrix_a)
print(matrix_b)
diff = matrix_a - matrix_b
print(diff)

[[5 5 1]
 [1 3 1]
 [8 5 7]]
[[6 1 4]
 [5 3 3]
 [9 3 4]]
[[-1  4 -3]
 [-4  0 -2]
 [-1  2  3]]


In [13]:
# substracting two matrices with different shapes
matrix_a=np.random.randint(1,10,size=(3,6))
matrix_b=np.random.randint(1,10,size=(3,3))
print(matrix_a)
print(matrix_b)
diff = matrix_a - matrix_b
print(diff)

[[9 5 9 6 9 4]
 [4 7 7 7 8 6]
 [4 6 9 2 6 4]]
[[6 5 2]
 [3 3 9]
 [5 6 8]]


ValueError: operands could not be broadcast together with shapes (3,6) (3,3) 

In [14]:
matrix_a=np.random.randint(1,10,size=(3,3))
matrix_b=np.random.randint(1,10,size=(3,3))
print(matrix_a)
print(matrix_b)
diff = np.subtract(matrix_a,matrix_b)
print(diff)

[[3 6 4]
 [4 2 3]
 [7 1 4]]
[[9 3 9]
 [1 3 8]
 [6 7 4]]
[[-6  3 -5]
 [ 3 -1 -5]
 [ 1 -6  0]]


2. Multiplication

- Rule: Number of cols in the first should be equal to number of rows

* By Scalar

In [16]:
x=5
matrix_a=np.random.randint(1,10,size=(3,3))
print('Matrix A:',matrix_a)
print('Scalar:',x)
print('Matrix X Scalar: ',x*matrix_a)

Matrix A [[8 3 6]
 [3 3 1]
 [9 2 5]]
Scalar 5
Matrix X Scalar  [[40 15 30]
 [15 15  5]
 [45 10 25]]


* By another matrix

In [27]:
matrix_a=np.random.randint(1,10,size=(5,3))
matrix_b=np.random.randint(1,10,size=(3,2))
print('Matrix A:',matrix_a)
print('Matrix B:',matrix_b)
product=np.dot(matrix_a,matrix_b)
print('Matrix Multiplication: ',product)

Matrix A: [[2 2 9]
 [3 5 6]
 [8 8 5]
 [5 9 2]
 [4 1 2]]
Matrix B: [[9 1]
 [9 7]
 [2 1]]
Matrix Multiplication:  [[ 54  25]
 [ 84  44]
 [154  69]
 [130  70]
 [ 49  13]]


In [26]:
matrix_a=np.random.randint(1,10,size=(5,3))
matrix_b=np.random.randint(1,10,size=(3,2))
print('Matrix A:',matrix_a)
print('Matrix B:',matrix_b)
product=np.multiply(matrix_a,matrix_b)
print('Matrix Multiplication: ',product)

Matrix A: [[6 9 6]
 [5 7 9]
 [5 3 7]
 [3 7 6]
 [5 3 2]]
Matrix B: [[7 9]
 [5 2]
 [9 3]]


ValueError: operands could not be broadcast together with shapes (5,3) (3,2) 