In [ ]:
import numpy as np
import matplotlib.pyplot as plt


Matrices Operations

1. Addition and Substraction

- Rule: Only Matrices with the same shape are allowed to add  and substract

In [9]:
# addition of the same shape
a=np.array(([1,3,5],[6,7,8]))
b=np.array(([1,3,5],[6,7,8]))
print(a+b)

[[ 2  6 10]
 [12 14 16]]


In [10]:
matrix_a=np.random.randint(1,10,size=(3,3))
matrix_b=np.random.randint(1,10,size=(3,3))
print(matrix_a)
print(matrix_b)
sum = matrix_a + matrix_b
print(sum)

[[1 7 5]
 [4 8 6]
 [8 6 3]]
[[6 5 6]
 [2 6 2]
 [8 8 4]]
[[ 7 12 11]
 [ 6 14  8]
 [16 14  7]]


In [11]:
matrix_a=np.random.randint(1,10,size=(4,3))
matrix_b=np.random.randint(1,10,size=(3,3))
print(matrix_a)
print(matrix_b)
sum = matrix_a + matrix_b
print(sum)

[[3 3 6]
 [4 7 6]
 [8 7 9]
 [7 7 5]]
[[9 6 4]
 [3 6 2]
 [3 4 7]]


ValueError: operands could not be broadcast together with shapes (4,3) (3,3) 

In [12]:
# Substaction
matrix_a=np.random.randint(1,10,size=(3,3))
matrix_b=np.random.randint(1,10,size=(3,3))
print(matrix_a)
print(matrix_b)
diff = matrix_a - matrix_b
print(diff)

[[5 5 1]
 [1 3 1]
 [8 5 7]]
[[6 1 4]
 [5 3 3]
 [9 3 4]]
[[-1  4 -3]
 [-4  0 -2]
 [-1  2  3]]


In [13]:
matrix_a=np.random.randint(1,10,size=(3,6))
matrix_b=np.random.randint(1,10,size=(3,3))
print(matrix_a)
print(matrix_b)
diff = matrix_a - matrix_b
print(diff)

[[9 5 9 6 9 4]
 [4 7 7 7 8 6]
 [4 6 9 2 6 4]]
[[6 5 2]
 [3 3 9]
 [5 6 8]]


ValueError: operands could not be broadcast together with shapes (3,6) (3,3) 